; Legilimens installer branding. electron-builder includes this file before its wizard
; template, so these defines apply to the pages it creates. Colours follow the website
; tokens: cream #EDE4D8 behind the header and Welcome/Finish text, ink #1E1611 for text.
; Artwork (icon.ico, installerSidebar.bmp, installerHeader.bmp) is generated by
; scripts/generate-installer-art.mjs.

!define MUI_BGCOLOR "EDE4D8"
!define MUI_TEXTCOLOR "1E1611"

!ifndef BUILD_UNINSTALLER
  !define MUI_FINISHPAGE_TITLE "Legilimens is ready"
  !define MUI_FINISHPAGE_TEXT "Open Legilimens, choose your upstream target in Connection settings, then point your test client at the local proxy.$\r$\n$\r$\nClick Finish to close Setup."
  !define MUI_FINISHPAGE_RUN_TEXT "Open Legilimens now"
!endif

!macro customWelcomePage
  !define MUI_WELCOMEPAGE_TITLE "Welcome to Legilimens"
  !define MUI_WELCOMEPAGE_TEXT "A closer look at your WebTransport traffic.$\r$\n$\r$\nSetup will install the Legilimens desktop app, a research preview for Windows x64. It runs locally and captures traffic only from clients you configure to connect through it.$\r$\n$\r$\nUse it with applications you own or have explicit permission to test.$\r$\n$\r$\nClick Next to continue."
  !insertmacro MUI_PAGE_WELCOME
!macroend
